### ISSUE TITLE
This comment highlight doesn't work, why?

### ISSUE THREAD

**Issue by frederikhors** [skellock/vscode-just#10]
![image](https://user-images.githubusercontent.com/41120635/168474676-8daec25b-255e-4184-ac23-7a3a62a02be6.png)

**Comment by kthy** [comment]
Because indented comments are not allowed? See just's [grammar](https://github.com/casey/just/blob/master/GRAMMAR.md) - comments are only allowed at the beginning of a line, or at the end of an assignment.
